
spring:
  profiles: dev
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/springsec101
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 3002